import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { localeHtml } from "./build/vite-locale-html.mjs";
import { LINKS } from "./src/data/links.js";

// `static/` is the publicDir, copied verbatim to the build root. It keeps the
// URLs search engines already index — /gup/public/* (OG card, icons,
// manifest), /gup/fonts/*, /gup/robots.txt, /gup/llms.txt — while the
// sitemap and the 404 are generated by scripts/prerender.mjs. Named "static"
// so its own public/ subfolder maps to /gup/public/ without colliding with
// Vite's default publicDir name.
const PUBLIC_DIR = "static";

export default defineConfig({
  base: LINKS.basePath,
  publicDir: PUBLIC_DIR,
  plugins: [react(), localeHtml()],
  build: {
    outDir: "dist",
    sourcemap: false,
    // Oxc, not esbuild: Vite 8 dropped esbuild from its dependency tree, and
    // `minify: "esbuild"` would require installing it separately.
    minify: "oxc",
    target: "es2020",
    assetsInlineLimit: 0,
    rollupOptions: {
      output: {
        // Rolldown (Vite 8) only accepts the function form of manualChunks.
        // `scheduler` is react-dom's own runtime dependency: leaving it out
        // would strand it in the entry chunk.
        manualChunks(id) {
          return /[\\/]node_modules[\\/](react|react-dom|scheduler)[\\/]/.test(id)
            ? "react"
            : undefined;
        },
      },
    },
  },
  server: {
    port: 5173,
    open: LINKS.basePath,
  },
});
