import type { Scene, SceneGroup } from "../scenes/scene.js";
import { REPORT_IMAGE } from "./report-image.js";

const HEADER = [
  "<!-- Generated by `npm run screenshots` from scripts/screenshots. Do not edit by hand. -->",
  "",
  "# Screenshots",
  "",
  "Every image below is the real interactive app, rendered headless on fixture data with a",
  "frozen clock: no real machine, package or path appears in them. The app runs its default",
  "theme (`terminal`) in a truecolor terminal using GitHub Dark Default, unless a section",
  "says otherwise; its text is English, the interface's default language (`gup language fr`",
  "switches it to French).",
  "`npm run screenshots` regenerates them; `npm run screenshots:check` fails when one is out",
  "of date. See [Documentation conventions](../../development/documentation.md#screenshots)",
  "to add one.",
];

const REPORT_ALT =
  "The HTML report's overview: a sentence summing up the period, key figures, the latest " +
  "weeks' calendar and the attempts per week.";

const REPORT_TITLE = "HTML report";
const REPORT_TEXT = [
  "The report `gup report` writes, captured in headless Chromium from the same fixture",
  "history by `npm run screenshots:report`. A browser's rendering differs from one machine",
  "to the next, so this image is regenerated by hand and never checked by CI.",
];

/** Punctuation that would end an image's text or open inline markup inside `![…]` or `**…**`. */
const MARKDOWN_SPECIAL = /[\\`*_[\]<>]/g;
/** A line break inside an image's text, a blank line especially, would end the paragraph. */
const LINE_BREAK = /\s*[\r\n]+\s*/g;

/** `text` as literal inline Markdown: one line, its markup characters escaped. */
function inlineText(text: string): string {
  return text.replace(LINE_BREAK, " ").replace(MARKDOWN_SPECIAL, "\\$&");
}

/** GitHub's anchor for a heading of plain words: lower case, spaces as dashes. */
function anchorOf(heading: string): string {
  return heading
    .toLowerCase()
    .replace(/[^a-z0-9 -]/g, "")
    .replace(/ /g, "-");
}

function contents(groups: readonly SceneGroup[]): string[] {
  const entries = [...groups.map((group) => group.title), REPORT_TITLE];
  return ["", ...entries.map((title) => `- [${inlineText(title)}](#${anchorOf(title)})`)];
}

function groupSection(group: SceneGroup): string[] {
  return ["", `## ${inlineText(group.title)}`, ...group.scenes.flatMap(sceneSection)];
}

/** The HTML report's picture, which another script captures (see {@link REPORT_IMAGE}). */
function reportSection(): string[] {
  return [
    "",
    `## ${REPORT_TITLE}`,
    "",
    ...REPORT_TEXT,
    "",
    `![${inlineText(REPORT_ALT)}](${REPORT_IMAGE})`,
  ];
}

function sceneSection(scene: Scene): string[] {
  const { cols, rows } = scene.size;
  return [
    "",
    `### ${scene.id}`,
    "",
    `**${inlineText(scene.title)}** · ${cols} × ${rows}`,
    "",
    `![${inlineText(scene.alt)}](${scene.id}.svg)`,
  ];
}

/**
 * The gallery page of `docs/assets/screens/`: contents, then a section per
 * group with each scene (id, window title, size, image), then the HTML
 * report's picture.
 */
export function renderGallery(groups: readonly SceneGroup[]): string {
  return [
    ...HEADER,
    ...contents(groups),
    ...groups.flatMap(groupSection),
    ...reportSection(),
    "",
  ].join("\n");
}
