import type { Scene } from "../scenes/scene.js";

const HEADER = [
  "<!-- Generated by `npm run screenshots` from scripts/screenshots. Do not edit by hand. -->",
  "",
  "# Screenshots",
  "",
  "Every image below is the real interactive app, rendered headless on fixture data with a",
  "frozen clock: no real machine, package or path appears in them. `npm run screenshots`",
  "regenerates them; `npm run screenshots:check` fails when one is out of date. See",
  "[Documentation conventions](../../development/documentation.md#screenshots) to add one.",
];

/** Punctuation that would end an image's text or open inline markup inside `![…]` or `**…**`. */
const MARKDOWN_SPECIAL = /[\\`*_[\]<>]/g;
/** A line break inside an image's text, a blank line especially, would end the paragraph. */
const LINE_BREAK = /\s*[\r\n]+\s*/g;

/** `text` as literal inline Markdown: one line, its markup characters escaped. */
function inlineText(text: string): string {
  return text.replace(LINE_BREAK, " ").replace(MARKDOWN_SPECIAL, "\\$&");
}

function section(scene: Scene): string[] {
  const { cols, rows } = scene.size;
  return [
    "",
    `## ${scene.id}`,
    "",
    `**${inlineText(scene.title)}** · ${cols} × ${rows}`,
    "",
    `![${inlineText(scene.alt)}](${scene.id}.svg)`,
  ];
}

/** The gallery page of `docs/assets/screens/`: one section per scene (id, title, size, image). */
export function renderGallery(scenes: readonly Scene[]): string {
  return [...HEADER, ...scenes.flatMap(section), ""].join("\n");
}
