/**
 * Regenerates src/data/facts.js from the repository itself.
 *
 * WHY THIS EXISTS: the landing page shipped "~130 providers", "v0.1.0" and
 * "Node >= 20" long after the CLI was at 134 providers, 0.3.1 and Node 22 —
 * across 40+ hand-maintained occurrences in the HTML head, the JSON-LD, the
 * FAQ, llms.txt, the manifest and the copy. Numbers a human has to keep in
 * sync drift, and every drifted number is a wrong answer served to Google and
 * to AI answer engines. So they are derived, once, at build time. The install
 * command is too: it is the README's, flags included, so the site can never
 * tell people to run something other than what the README does.
 *
 * Runs as the `prebuild`/`predev` hook, so `npm run dev` and `npm run build`
 * both regenerate it. The output IS committed: it must exist for a bare
 * `vite build` and for editor tooling.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { readInstallCommand } from "../build/facts/read-install-command.mjs";
import { readNodeFloor } from "../build/facts/read-node-floor.mjs";
import { readRegistry } from "../build/facts/read-registry.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../..");
const out = resolve(here, "../src/data/facts.js");
/** Far below the real registry: a smaller count means the ALL_PROVIDERS shape changed. */
const MIN_PLAUSIBLE_PROVIDERS = 100;

const readRepo = (path) => readFileSync(resolve(repoRoot, path), "utf8");
const pkg = JSON.parse(readRepo("package.json"));
const { providerCount, providersByDomain, providersBySystem } = readRegistry(
  readRepo("src/core/registry.ts"),
  (relative) => readRepo(`src/providers/${relative}.ts`),
);

if (providerCount < MIN_PLAUSIBLE_PROVIDERS) {
  throw new Error(
    `sync-facts: counted only ${providerCount} providers in src/core/registry.ts — ` +
      "the ALL_PROVIDERS shape probably changed. Fix build/facts/read-registry.mjs rather " +
      "than hardcoding the number back into the site.",
  );
}

// The floor gup enforces at start ("26.9.0"), not engines.node
// (build/facts/read-node-floor.mjs). The copy shows the major ("Node ≥ 26");
// the structured data states the exact minimum.
const nodeEngine = readNodeFloor(readRepo("src/core/node-floor.ts"));
const nodeMajor = nodeEngine.split(".")[0];

const installCommand = readInstallCommand(readRepo("README.md"), pkg.name);

const facts = `// GENERATED by scripts/sync-facts.mjs — do not edit by hand.
// Derived from the repository root package.json and README.md, src/core/registry.ts
// and the provider sources it registers, and src/core/node-floor.ts. Run
// \`npm run sync:facts\` (or any build) to refresh.

export const facts = {
  /** Published npm version, from the root package.json. */
  version: ${JSON.stringify(pkg.version)},
  /** Number of entries in ALL_PROVIDERS (src/core/registry.ts). */
  providerCount: ${providerCount},
  /** Minimum Node major, from MIN_NODE in src/core/node-floor.ts (${JSON.stringify(nodeEngine)}). */
  nodeMajor: ${Number(nodeMajor)},
  /** Exact minimum Node version — used by the JSON-LD softwareRequirements. */
  nodeEngine: ${JSON.stringify(nodeEngine)},
  /** npm package name: the npm links, the JSON-LD and the llms texts. */
  packageName: ${JSON.stringify(pkg.name)},
};

/** Provider ids grouped by their domain folder under src/providers/. */
export const providersByDomain = ${JSON.stringify(providersByDomain, null, 2)};

/**
 * Registered providers gup supports on each system, from their
 * \`readonly platforms = PLATFORMS.<set>;\` declarations (none: every system).
 */
export const providersBySystem = ${JSON.stringify(providersBySystem, null, 2)};

/**
 * The one command the whole page is trying to get people to run: the README's
 * install line, verbatim, flags included (build/facts/read-install-command.mjs).
 */
export const installCommand = ${JSON.stringify(installCommand)};
`;

writeFileSync(out, facts, "utf8");
const perSystem = Object.entries(providersBySystem)
  .map(([system, count]) => `${system} ${count}`)
  .join(", ");
process.stdout.write(
  `sync-facts: v${pkg.version} · ${providerCount} providers (${perSystem}) · ` +
    `Node >= ${nodeMajor}\n`,
);
