/**
 * Regenerates src/data/facts.js from the repository itself.
 *
 * WHY THIS EXISTS: the landing page shipped "~130 providers", "v0.1.0" and
 * "Node >= 20" long after the CLI was at 134 providers, 0.3.1 and Node 22 —
 * across 40+ hand-maintained occurrences in the HTML head, the JSON-LD, the
 * FAQ, llms.txt, the manifest and the copy. Numbers a human has to keep in
 * sync drift, and every drifted number is a wrong answer served to Google and
 * to AI answer engines. So they are derived, once, at build time.
 *
 * Runs as the `prebuild`/`predev` hook, so `npm run dev` and `npm run build`
 * both regenerate it. The output IS committed: it must exist for a bare
 * `vite build` and for editor tooling.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../..");
const out = resolve(here, "../src/data/facts.js");

const pkg = JSON.parse(
  readFileSync(resolve(repoRoot, "package.json"), "utf8"),
);
const registry = readFileSync(
  resolve(repoRoot, "src/core/registry.ts"),
  "utf8",
);

/**
 * Counts the `new XProvider(),` entries of ALL_PROVIDERS. Deliberately a
 * regex over the source rather than an import: the CLI is TypeScript ESM
 * compiled with tsup, and making the landing build depend on the CLI build
 * would couple two independent pipelines for one integer.
 */
function countProviders(source) {
  const body = source.slice(source.indexOf("export const ALL_PROVIDERS"));
  const matches = body.match(/^\s+new [A-Za-z0-9_]+\(\),$/gm);
  return matches ? matches.length : 0;
}

/**
 * The REGISTERED provider ids, grouped by their domain folder under
 * src/providers/.
 *
 * Feeds the provider inventory in llms-full.txt — the one dataset on this site
 * that exists nowhere else in a quotable form, and exactly what an AI answer
 * engine needs to answer "does gup cover X". Derived from the sources so it
 * cannot fall behind, the way the old hand-written 130-row copy in the landing
 * bundle did.
 *
 * Walked from ALL_PROVIDERS rather than from the filesystem on purpose: there
 * are provider FILES under src/providers/ that the registry does not
 * instantiate, so a directory listing yields more ids than the CLI actually
 * runs — and publishing a longer list than the advertised count would be a
 * claim the tool does not honour.
 */
function registeredProviders(source, root) {
  const body = source.slice(source.indexOf("export const ALL_PROVIDERS"));
  const instantiated = new Set(
    (body.match(/^\s+new ([A-Za-z0-9_]+)\(\),$/gm) ?? []).map((line) =>
      line.trim().slice(4, -3),
    ),
  );

  const groups = {};
  const importRe =
    /import\s*\{\s*([A-Za-z0-9_,\s]+?)\s*\}\s*from\s*"\.\.\/providers\/([^"]+)\.js"/g;
  for (const [, symbols, relative] of source.matchAll(importRe)) {
    if (!symbols.split(",").some((s) => instantiated.has(s.trim()))) continue;
    // `self.ts` sits at the root of src/providers/ rather than in a domain
    // folder — it is gup updating itself.
    const domain = relative.includes("/") ? relative.split("/")[0] : "self";
    const found = readFileSync(
      resolve(root, "src/providers", `${relative}.ts`),
      "utf8",
    ).match(/\bid\s*=\s*"([a-z0-9.@/-]+)"/i);
    if (!found) continue;
    (groups[domain] ??= []).push(found[1]);
  }

  for (const ids of Object.values(groups)) ids.sort();
  return groups;
}

const providerCount = countProviders(registry);
const domains = registeredProviders(registry, repoRoot);
const listedCount = Object.values(domains).reduce((n, ids) => n + ids.length, 0);
if (listedCount !== providerCount) {
  throw new Error(
    `sync-facts: extracted ${listedCount} provider ids but ALL_PROVIDERS holds ` +
      `${providerCount}. The site must not publish a list that disagrees with ` +
      "the count — fix registeredProviders() before shipping.",
  );
}
if (providerCount < 100) {
  throw new Error(
    `sync-facts: counted only ${providerCount} providers in src/core/registry.ts — ` +
      "the ALL_PROVIDERS shape probably changed. Fix countProviders() rather " +
      "than hardcoding the number back into the site.",
  );
}

// engines.node is a semver range (">=22.13.0"). The copy shows the major
// ("Node ≥ 22"); the structured data states the exact minimum.
const nodeEngine = (pkg.engines?.node ?? "").replace(/[^\d.]/g, "");
const nodeMajor = nodeEngine.split(".")[0];
if (!nodeMajor) {
  throw new Error("sync-facts: could not read engines.node from package.json");
}

const facts = `// GENERATED by scripts/sync-facts.mjs — do not edit by hand.
// Derived from the repository root package.json and src/core/registry.ts.
// Run \`npm run sync:facts\` (or any build) to refresh.

export const facts = {
  /** Published npm version, from the root package.json. */
  version: ${JSON.stringify(pkg.version)},
  /** Number of entries in ALL_PROVIDERS (src/core/registry.ts). */
  providerCount: ${providerCount},
  /** Minimum Node major, from engines.node (${JSON.stringify(pkg.engines?.node ?? "")}). */
  nodeMajor: ${Number(nodeMajor)},
  /** Exact minimum Node version — used by the JSON-LD softwareRequirements. */
  nodeEngine: ${JSON.stringify(nodeEngine)},
  /** npm package name, used by every install snippet on the page. */
  packageName: ${JSON.stringify(pkg.name)},
};

/** Provider ids grouped by their domain folder under src/providers/. */
export const providersByDomain = ${JSON.stringify(domains, null, 2)};

/** The one command the whole page is trying to get people to run. */
export const installCommand = \`npm install -g \${facts.packageName}\`;
`;

writeFileSync(out, facts, "utf8");
process.stdout.write(
  `sync-facts: v${pkg.version} · ${providerCount} providers · Node >= ${nodeMajor}\n`,
);
